config/routes.rb
Microblog::Application.routes.draw do
  get "home" => "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  
  root "static_pages#home"
  
  get "signup" => "users#new"

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  
  get "signin" => "sessions#new"
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<section class="container">
		<!-- row 1: navigation -->
    <div class="row">
        <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
            	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse" >
                    <span class="src-only"></span>   
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Sample App</a>
            </div> 
            <div class="collapse navbar-collapse" id="collapse">
                <ul class="nav navbar-nav pull-right">
                    <li> <%= link_to "Home", home_path %> </li>
					<li> <%= link_to "Help", help_path %> </li>
                    <% if signed_in? %>
                        <li><%= link_to "Users", users_path %></li>
                        <li id="fat-menu" class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                          </a>
                          <ul class="dropdown-menu">
                            <li><%= link_to "Profile", current_user %></li>
                            <%= link_to "Settings", edit_user_path(current_user) %>
                            <li class="divider"></li>
                            <li>
                              <%= link_to "Sign out", signout_path, method: "delete" %>
                            </li>
                          </ul>
                        </li>
                    <% else %>
                        <li><%= link_to "Sign in", signin_path %></li>
                    <% end %>
                </ul>
            </div>
        </nav> 
    </div> <!-- navigation -->
</section>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(@title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
	        <div class="alert alert-<%= key %>"><%= value %></div>
	      <% end %>
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>